runtime: python311 # or another supported version

# Machine config  https://cloud.google.com/appengine/docs/standard
instance_class: B2
manual_scaling:
  instances: 1
# Timeout is 60sec
entrypoint: gunicorn -b :$PORT app:server --timeout 60 --workers 1
# Instance name
service: default
handlers:
  - url: /.*
    script: auto
    secure: always

