---
title: "Crop Performance Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme:
      bootswatch: minty
      version: 4
      base_font: 
        google: Roboto
      heading_font:
        google: Sen
      code_font:
        google: 
          # arguments to sass::font_google() 
          family: JetBrains Mono
          local: false
runtime: shiny
---

```{r setup}
library(bslib)
library(shiny)
library(flexdashboard)
library(shinydashboard)
library(shinyWidgets)
library(dplyr)
library(DT)

source("R/data_loader.r")
```

# Tests
## test
```{r}
str(maizeSites)
str(soybeanSites)
str(maize)
str(soybean)
```

# Data
### Table Data

```{r}
selectInput("crop_select", "Dataset Selection", c("Maize Sites", "Soybean Sites", "Maize", "Soybean"))
DTOutput("table")

output$table <- renderDT(
  df_list[[input$crop_select]],
  options = list(
    columnDefs = list(list(className = 'dt-left', targets = '_all')), 
    pageLength = 25
    )
  )
```

# About

## Column {data-width="700"}

### About this project
``` {r child = 'ui_components/about.Rmd'}
```