dash:
  app_title: Crop Trials Visualization Tool
  update_title: Updating...
  theme: LUMEN
  debug: True

data:
  corn_path: /mnt/c/Users/phcis/croptrials_vis_prototype/data/datasets/corn.csv
  soybean_path: /mnt/c/Users/phcis/croptrials_vis_prototype/data/datasets/soybean.csv
  sunflower_path: /mnt/c/Users/phcis/croptrials_vis_prototype/data/datasets/sunflower.csv
  wheat_path: /mnt/c/Users/phcis/croptrials_vis_prototype/data/datasets/wheat.csv
  county_path: /mnt/c/Users/phcis/croptrials_vis_prototype/data/datasets/county_data.csv
  geodata_path: /mnt/c/Users/phcis/croptrials_vis_prototype/data/datasets/us-county-boundaries.geojson

template:
  logo_src: ../assets/KSU-Crops-logo.png
  fa_logo_src: ../assets/chart-line-solid.svg
  about_img_src: ../assets/cg-kansasstate-farm.jpg

version: v0.0.1
github_url: https://github.com/cisdeli
github_repo: sprmbng/
ciampitti_url: https://ciampittilab.wixsite.com/ciampitti-lab
paper_url: https://arxiv.org/
