dash:
  app_title: Crop Trials Visualization Tool
  update_title: Updating...
  theme: LUMEN
  debug: True

data:
  corn_path: /home/sprmbng/Desktop/croptrials_vis_prototype/data/datasets/1982-2020_corn.csv
  soybean_path: /home/sprmbng/Desktop/croptrials_vis_prototype/data/datasets/1991-2022_soybean.csv
  sunflower_path: /home/sprmbng/Desktop/croptrials_vis_prototype/data/datasets/1998-2019_sunflower.csv
  wheat_path: /home/sprmbng/Desktop/croptrials_vis_prototype/data/datasets/1982-2022_wheat.csv

template:
  logo_src: ../assets/KSU-Crops-logo.png

version: v0.0.1
github_url: https://github.com/sprmbng
github_repo: sprmbng/
