dash:
  app_title: Crop Trials Visualization Tool
  update_title: Updating...
  theme: LUMEN
  debug: True

data:
  corn_path: /home/sprmbng/Desktop/croptrials_vis_prototype/data/datasets/corn.csv
  soybean_path: /home/sprmbng/Desktop/croptrials_vis_prototype/data/datasets/soybean.csv
  sunflower_path: /home/sprmbng/Desktop/croptrials_vis_prototype/data/datasets/sunflower.csv
  wheat_path: /home/sprmbng/Desktop/croptrials_vis_prototype/data/datasets/wheat.csv
  county_path: /home/sprmbng/Desktop/croptrials_vis_prototype/data/datasets/county_data.csv

template:
  logo_src: ../assets/KSU-Crops-logo.png
  about_img_src: ../assets/cg-kansasstate-farm.jpg

version: v0.0.1
github_url: https://github.com/sprmbng
github_repo: sprmbng/
